### PR TITLE
Added sign on page to app.js with tailwind formatting.  Added .env fi…

### PR DESCRIPTION
**Pull request by EsmondKim**
Added a sign on page to app.js with tailwind css styling.  Besides installing local dependencies, the repo should now be formatted to work with React and Tailwindcss.  Added require('dotenv').config()  to server.js and started a .env file.

### CODE REVIEW

**Comment by Kay0s** [comment]
@EsmondKim Should this pull request be reviewed?  Or is this branch still in progress?

**Comment by EsmondKim** [comment]
Hey, I forgot to lint so I rolled back my last commit with git reset --soft
HEAD~1
I'll try to lint and redo the commit right now so it can be approved and
we've got some css to work with.

Esmond

**Comment by Kay0s** [comment]
@EsmondKim Thanks for the update!

Add to your package.json scripts
"fix: "eslint **/*.js --fix","
And then run in the terminal, npm run fix
That should try to auto-fix and linting issues.

image

**Comment by EsmondKim** [comment]
I closed out this pull request, and created a whole new pull request.  The travis check should be running as we speak.  npm run fix worked for me before pushing, and the sign on page is working for me locally before this new pull request.  Please feel free to review and approve the new request when Travis is done.

**Pull request closed without merging**
